# This is a basic workflow to help you get started with Actions

name: checking actions behaviour on time limits

# Controls when the action will run. 
on:
  push:
    branches:
      - main
  # Only manually, we really don't want to make this one happen too much
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.x
          
      - name: Print out the version
        run: python --version

      # a command which never finishes.
      - name: Run a one-line script
        run: timeout 20s python ./forever.py || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
